
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGNACION CAN COMA DEFPROC DEFVAR DROP EAST ELSE FACING IF JUMP LETGO LLAVEDER LLAVEIZQ MOVE NAME NO NOP NORTH NUMBER OTHER_ACTION PARDER PARIZ PICK_UP PUTCB REPEAT SEMICOLON SOUTH TIMES TURN WALK WEST WHILE YES\n    program : commands\n    \n    commands : command\n             | commands command\n    \n    command : simple_command\n    \n    simple_command : YES\n                   | NO\n    '
    
_lr_action_items = {'YES':([0,2,3,4,5,6,7,],[5,5,-2,-4,-5,-6,-3,]),'NO':([0,2,3,4,5,6,7,],[6,6,-2,-4,-5,-6,-3,]),'$end':([1,2,3,4,5,6,7,],[0,-1,-2,-4,-5,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'commands':([0,],[2,]),'command':([0,2,],[3,7,]),'simple_command':([0,2,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> commands','program',1,'p_program','proyecto0_parser.py',9),
  ('commands -> command','commands',1,'p_commands','proyecto0_parser.py',15),
  ('commands -> commands command','commands',2,'p_commands','proyecto0_parser.py',16),
  ('command -> simple_command','command',1,'p_command','proyecto0_parser.py',25),
  ('simple_command -> YES','simple_command',1,'p_simple_command','proyecto0_parser.py',31),
  ('simple_command -> NO','simple_command',1,'p_simple_command','proyecto0_parser.py',32),
]
